<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Utilisateur de l'administration
 *
 * @ORM\Entity(repositoryClass="App\Repository\ContributorRepository")
 * @ORM\Table()
 * @UniqueEntity(fields={"email"}, message="E-mail déjà enregistré.")
 */
class Contributor implements UserInterface
{
    public const ROLE_SUPERADMIN = 'ROLE_SUPERADMIN';
    public const ROLE_ADMIN = 'ROLE_ADMIN';

    /**
     * Id de l'utilisateur
     *
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * Nom complet de l'utilisateur
     *
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Information requise.")
     */
    private ?string $fullname = null;

    /**
     * Email de l'utilisateur
     *
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Information requise.")
     * @Assert\Email(message="Email incorrect.")
     */
    private ?string $email = null;

    /**
     * Mot de passe
     *
     * @ORM\Column(type="string", length=255)
     */
    private ?string $password = null;

    /**
     * Mot de passe en clair (non persisté)
     *
     * @Assert\NotBlank(message="Information requise.", groups={"creation"})
     */
    public ?string $plainPassword = null;

    /**
     * Niveau de droits
     *
     * @ORM\Column(type="string", length=255)
     */
    private ?string $role = null;

    /**
     * <@inheritDoc>
     */
    public function getUsername(): ?string
    {
        return $this->email;
    }

    /**
     * <@inheritDoc>
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    /**
     * <@inheritDoc>
     */
    public function getRoles(): array
    {
        return $this->getRole() ? [$this->getRole()] : [];
    }

    /**
     * <@inheritDoc>
     */
    public function getSalt()
    {
        return null;
    }

    /**
     * <@inheritDoc>
     */
    public function eraseCredentials()
    {
    }

    /**
     * Retourne les rôles disponibles
     */
    public static function getAvailableRoles(): array
    {
        return [
            self::ROLE_ADMIN => 'Administrateur',
            self::ROLE_SUPERADMIN => 'Super Administrateur'
        ];
    }

    /**
     * Retourne le label du rôle de l'utilisateur
     */
    public function getRoleAsLabel(): string
    {
        $availableRoles = self::getAvailableRoles();

        return $availableRoles[$this->getRole()] ?? '';
    }

    /**
     * L'utilisateur est-il supprimable ?
     */
    public function isDeletable(): bool
    {
        return $this->getRole() != self::ROLE_SUPERADMIN;
    }

    /***********************************************/
    /*           AUTOGENERATED CODE BELLOW         */
    /***********************************************/

    public function getId()
    {
        return $this->id;
    }

    public function getFullname(): ?string
    {
        return $this->fullname;
    }

    public function setFullname(string $fullname): self
    {
        $this->fullname = $fullname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(string $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getUserIdentifier(): string
    {
        // TODO: Implement getUserIdentifier() method.
        return $this->getEmail();
    }
}
