<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

trait TraitPositionable
{
    /**
     * Position / Ordonnancement
     *
     * @ORM\Column(type="smallint", nullable=false)
     */
    private ?int $position = null;

    /***********************************************/
    /*           AUTOGENERATED CODE BELLOW         */
    /***********************************************/

    public function getPosition(): ?int
    {
        return $this->position;
    }

    public function setPosition(?int $position): void
    {
        $this->position = $position;
    }
}
