<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

#[ORM\Table()]
#[ORM\Entity()]
#[ORM\Index(columns: ['product_id', 'user_id'], name: 'ecommerce_wishlists')]
#[ORM\HasLifecycleCallbacks]
class Wishlist
{
    use TraitTimestamp;
    use TraitToken;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    /**
     * Nom du pays.
     */
    #[ORM\ManyToOne(targetEntity: Product::class)]
    private Product $product;

    #[ORM\ManyToOne(targetEntity: User::class)]
    private User $user;

    // AUTOGENERATED CODE BELLOW

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProduct(): Product
    {
        return $this->product;
    }

    public function setProduct(Product $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getUser(): User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }
}
