# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    messenger: true
    driver: "imagick"
    twig:
        mode: lazy
    default_filter_set_settings:
        format: webp
    # configure webp
    webp:
        generate: true
    controller:
        redirect_response_code: 302

    filter_sets:
        # profil filters
        profil:
            quality: 100
            filters:
                auto_rotate: ~
                downscale:
                    max: [ 315, 315 ]
        profil_miniature:
            quality: 100
            filters:
                auto_rotate: ~
                thumbnail: { size: [ 200, 200 ], mode: outbound, allow_upscale: true }

        ## home page filters
        home_slider:
            quality: 100
            filters:
                auto_rotate: ~
                #downscale:
                 #   max: [ 1920, 933 ]
                fixed:
                    width: 1254
                    height: 750
        home_under_slider:
            quality: 100
            filters:
                auto_rotate: ~
                fixed:
                    width: 376
                    height: 233
        home_mid:
            quality: 100
            filters:
                auto_rotate: ~
                downscale:
                    max: [ 950, 457 ]

        home_latest:
            quality: 100
            filters:
                auto_rotate: ~
                downscale:
                    max: [ 240, 125 ]

        # product filters
        product_modal:
            quality: 100
            filters:
                auto_rotate: ~
                #strip: ~
                downscale:
                    max: [ 316, 403 ]
        product_modal_miniature:
            quality: 100
            filters:
                auto_rotate: ~
                #strip: ~
                downscale:
                    max: [ 102, 130 ]
        product_trends_or_sale:
            quality: 100
            filters:
                auto_rotate: ~
                #strip: ~
                #downscale:
                    #max: [ 270, 344 ]
                fixed:
                    width: 270
                    height: 344
        product_details:
            quality: 100
            filters:
                auto_rotate: ~
                #strip: ~
                downscale:
                    max: [ 470, 600 ]
        product_miniature_details:
            quality: 100
            filters:
                auto_rotate: ~
                #strip: ~
                downscale:
                    max: [ 90, 115 ]
        product_miniature:
            quality: 100
            filters:
                auto_rotate: ~
                #strip: ~
                thumbnail: { size: [ 130, 130 ], mode: outbound, allow_upscale: true }
