name: Build

on:
    pull_request:
        types:
            - closed

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v2

            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.2'

            -   name: Install Composer dependencies
                run: "
                    cd app &&
                    composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist -o &&
                    php bin/console fos:js-routing:dump --format=json --target=public/js/fos_js_routes.json &&
                    composer dump-autoload --no-dev --classmap-authoritative --optimize"

            -   name: Install latest Node.js and Yarn
                uses: actions/setup-node@v3
                with:
                    node-version: '21'
                    registry-url: 'https://registry.npmjs.org/'

            -   run: |
                    cd app
                    yarn install

            -   name: Build node assets and check Lint
                run: |
                    cd app
                    yarn encore production
                    php bin/console doctrine:schema:validate --skip-sync -q
                    php bin/console lint:twig templates
                    php bin/console lint:yaml config

            -   name: Trigger Deploy Workflow
                if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
                uses: peter-evans/repository-dispatch@v2
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    event-type: deploy