name: Deploy to Hostinger

on:
    workflow_run:
        workflows: [ "Build" ]
        types:
            - completed

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v2

            -   name: Deploy to Hostinger
                if: github.event.workflow_run.conclusion == 'success'
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.HOSTINGER_HOST }}
                    username: ${{ secrets.HOSTINGER_USERNAME }}
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    script: |
                        cd /app
                        rsync -r --delete-after --quiet $GITHUB_WORKSPACE/app ${{ env.username }}@${{ env.host }}:~/domains/reented.com/
                        ssh ${{ env.username }}@${{ env.host }} 'cd ~/domains/reented.com/ && export APP_ENV=prod && composer install --no-ansi --no-interaction --no-progress --optimize-autoloader'
                        ssh ${{ env.username }}@${{ env.host }} 'cd ~/domains/reented.com/ && export APP_ENV=prod && composer dump-autoload --optimize'
                        ssh ${{ env.username }}@${{ env.host }} 'cd ~/domains/reented.com/ && export APP_ENV=prod && php bin/console d:s:u -f'
                        ssh ${{ env.username }}@${{ env.host }} 'cd ~/domains/reented.com/ && export APP_ENV=prod && php bin/console cache:clear'
                        ssh ${{ env.username }}@${{ env.host }} 'cd ~/domains/reented.com/ && export APP_ENV=prod && cp public/. public_html/ -R'
